on:
  push:
    branches:
      - test


jobs:
  
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: "login to dockerhub"
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASS }}
      
    - name: "build the docker image"
      run : docker build -t ${{ secrets.DOCKER_USERNAME }}/img301 .  
      
    - name: "push the image to dockerhub"
      run: docker push ${{ secrets.DOCKER_USERNAME }}/img301 
    
    

